sudo: required
services: 
    - docker

before_install:
    - docker build -t simonb1/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run  simonb1/react-test npm test -- --coverage

after_succes:
    - docker build -t simonb1/multi-client ./client
    - docker build -t simonb1/multi-nginx ./nginx
    - docker build -t simonb1/multi-server ./server
    - docker build -t simonb1/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push simonb1/multi-client
    - docker push simonb1/multi-nginx
    - docker push simonb1/multi-server
    - docker push simonb1/multi-worker